Repository ALTA-LapakUMKM-Group-2/LapakUMKM-FE, pull requests merged in 2023-03, with the labels that each got.

#70 style: darkmode , Refactor: detail , toko penjual
  src/App.tsx
  src/components/CardFeedback.tsx
  src/components/ChatModal.tsx
  src/components/Layout.tsx
  src/components/Navbar.tsx
  src/components/ProdukCard.tsx
  src/pages/Cart.tsx
  src/pages/Detail.tsx
  src/pages/HistoryPembeli.tsx
  src/pages/Home.tsx
  src/pages/HomeFilterPage.tsx
  src/pages/ListProduct.tsx
  src/pages/Payment.tsx
  src/pages/Profile.tsx
  src/pages/Toko.tsx
Labels: bug, enhancement

#73 Test Deploy Pase 1
  index.html
  src/App.tsx
  src/components/Navbar.tsx
  src/pages/CallbackSSO.tsx
  src/pages/Home.tsx
  src/pages/HomeFilterPage.tsx
  src/pages/ListProduct.tsx
  src/pages/Login.tsx
  src/pages/Payment.tsx
Labels: documentation

#76 refactor: fixed function in checkbox
  src/components/CartCard.tsx
  src/pages/Cart.tsx
  src/pages/Payment.tsx
Labels: bug

#77 Feat: function payment , style: Darkmode payment
  src/components/Navbar.tsx
  src/pages/Detail.tsx
  src/pages/ListProduct.tsx
  src/pages/Login.tsx
  src/pages/Payment.tsx
  src/pages/Profile.tsx
  src/pages/Toko.tsx
Labels: good first issue

#83 user without token cant go to detail
  package-lock.json
  package.json
  src/components/Navbar.tsx
  src/components/ProdukCard.tsx
  src/pages/Home.tsx
  src/pages/Profile.tsx
Labels: bug, enhancement

#86 Deploy
  src/components/CardHistory.tsx
  src/components/Modal.tsx
  src/components/Navbar.tsx
  src/pages/Detail.tsx
  src/pages/HistoryPembeli.tsx
  src/pages/NotifikasiCoba.tsx
  src/pages/Register.tsx
  src/pages/Toko.tsx
Labels: bug, enhancement
